### ISSUE TITLE
Deleted file appears under Other manufacturer list

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaApp-Omero#20]
File was deleted from "Microscopes" dataset list.
![image](https://user-images.githubusercontent.com/4050585/115170884-b7d6b080-a08f-11eb-85ea-e9100abe18fa.png)

However, it appears as available on the list of available Microscopes under the "Other" manufacturer list.

![image](https://user-images.githubusercontent.com/4050585/115170988-fc624c00-a08f-11eb-9ff3-d3681dbec598.png)

![image](https://user-images.githubusercontent.com/4050585/115170954-e48ac800-a08f-11eb-9a3d-9eb20a556caf.png)

**Comment by Akramhar** [comment]
this is a issue with omero attachments, should be now solved
